date_since = "2022-01-05T18:00:00Z"
feed_urls = [
	"https://rekt.news/rss/feed.xml", 
	"https://future.a16z.com/feed", 
	"https://blog.ethereum.org/feed.xml", 
	"https://newsletter.banklesshq.com/feed", 
	"https://www.theblockcrypto.com/rss.xml", 
	"https://www.coindesk.com/arc/outboundfeeds/rss/?outputType=xml",
	"https://decrypt.co/feed", 
	"https://vitalik.ca//./feed.xml", 
	"http://feeds.feedburner.com/ConsenSys/posts?format=xml", 
	"https://rsshub.app/telegram/channel/thedailyape", 
	"https://medium.com/feed/@ambergroup", 
	"https://medium.com/feed/@polynya"
]
webhook_url = ""
